### PR TITLE
BadApple -> Video to text

### PR DESCRIPTION
**Pull request by yeonfish6040**
Improve build time.
Can change other video to text

### bad apple
npm run prepare && npm start

### other videos
file=filepath npm run prepare

or

npm run extract filepath
npm run build

and 

npm start

### CODE REVIEW

**Comment by KineticTactic** [comment]
Hey, thanks for your contribution! This was a much needed update.

The only thing I'd like to point out is the argument passing, can you change this line in package.json
```
"prepare": "node extractFrames ${file} && node build",
```
and instead use post scripts 
```
"prepare": "node extractFrames",
"postprepare": "node build",
```
so then, we can directly pass the filename as such
```
npm run prepare res/file.mp4
```

And can you update commands in the README?

Everything else looks pretty good, I'll merge it once you make the changes.

**Comment by yeonfish6040** [comment]
Got it :). I'll update this PR as soon as i can!

**Comment by yeonfish6040** [comment]
Complete!

**Comment by KineticTactic** [comment]
Perfect, I'll make a contributors section in the README and mention you there :)

**Comment by yeonfish6040** [comment]
> Perfect, I'll make a contributors section in the README and mention you there :)

It's an honor. Thank you so much

**Pull request merged**
